name: Deploy HTML Report

on:
  push:
    branches:
      - HTML_REPORT  # Trigger when pushing to the html-report branch

jobs:
  deploy-html-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress\reports # Directory containing your HTML report files
          publish_branch: HTML_REPORT  # Branch to deploy to
