name: Deploy HTML Report to GitHub Pages

on: 
  push: 
    branches:
      - master  # or the branch where the report is generated

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate HTML report
        run: |
          mv cypress/reports/html/index.html .  # Move index.html to root
          mv cypress/reports/html/assets ./assets  # Move assets directory to root

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Root directory
          publish_branch: html-reports  # Branch to deploy to
